import React from 'react'
import { useLocation } from 'react-router-dom';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemAvatar from '@mui/material/ListItemAvatar';
import ListItemText from '@mui/material/ListItemText';
import Avatar from '@mui/material/Avatar';
import Rating from '@mui/material/Rating';
import { Divider } from '@mui/material';
import { useState } from 'react';
import { TextField } from '@mui/material';
import Button from '@mui/material/Button';
import iphone from '../../assets/iphone.png'
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Typography from '@mui/material/Typography';
import { Grid } from '@mui/material';

const Produto = () => {
    const { state } = useLocation();

    const [comment, setComment] = useState('');
    const [rating, setRating] = useState(0);

    const messages = [
        {
          primary: 'Brunch this week?',
          secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
          rating: 3
        },
        {
          primary: 'Birthday Gift',
          secondary: `Do you have a suggestion for a good present for John on his work
            anniversary. I am really confused & would love your thoughts on it.`,
            rating: 4
        },
        {
          primary: 'Recipe to try',
          secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
          rating: 5
        },
        {
          primary: 'Yes!',
          secondary: 'I have the tickets to the ReactConf for this year.',
          rating: 2
        },
        {
          primary: "Doctor's Appointment",
          secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
          rating: 1
        },
        {
          primary: 'Discussion',
          secondary: `Menus that are generated by the bottom app bar (such as a bottom
            navigation drawer or overflow menu) open as bottom sheets at a higher elevation
            than the bar.`,
            rating: 5
        },
        {
          primary: 'Summer BBQ',
          secondary: `Who wants to have a cookout this weekend? I just got some furniture
            for my backyard and would love to fire up the grill.`,
            rating: 5
        },
      ];
  return (
    <>
        <Box sx={{ pb: 7 }}>
            <CssBaseline />
            <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', p: 2 }}>
                <Card sx={{ width: '100%' }}>
                    <CardMedia
                        component="img"
                        height="180"
                        width="300"  
                        image={iphone}
                        alt="Iphone X"
                        sx={{ objectFit: 'contain' }}
                    />
                    <CardContent>
                        <Typography gutterBottom variant="h5" component="div">
                            Iphone X
                        </Typography>
                        <Grid mt={1}>
                            <Rating name="read-only" value={5} readOnly />
                        </Grid>
                    </CardContent>
                </Card>
            </Box>
            <Box display="flex" alignItems="center" padding="20px" gap="30px">
                <Avatar alt="Avatar" />
                <TextField
                    fullWidth
                    variant="outlined"
                    placeholder="Insira seu comentário aqui..."
                    value={comment}
                    onChange={(e) => setComment(e.target.value)}
                />
                <Rating
                    name="rating"
                    value={rating}
                    onChange={(e) => setRating(e.target.value)}
                />
                <Button variant="contained" color="error">
                    Enviar
                </Button>
            </Box>
            <Divider variant="inset" component="li" />
            <List>
                {messages.map(({ primary, secondary, rating }, index) => (
                    <ListItem key={index}>
                        <ListItemAvatar>
                            <Avatar alt="Profile Picture" />
                        </ListItemAvatar>
                        <ListItemText primary={primary} secondary={secondary} />
                        <Rating name="read-only" value={rating} readOnly />
                    </ListItem>
                ))}
            </List>
        </Box>
    </>
  )
}

export default Produto